version: "3.3"

services:
  ddns-service:
    build: .
    # image: ghcr.io/timurvafin/ddns:latest
    restart: unless-stopped
    environment:
      - TZ
      - PUID
      - PGID
      - TOKEN=${DNSIMPLE_HORSE_TOKEN}
      - ACCOUNT_ID=${DNSIMPLE_ACCOUNT_ID}
      - HOSTNAME=${DNSIMPLE_HOSTNAME}
